In [1]:
import os
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from numpy import asarray
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/chap/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/chap/' #home directory of the project
TRAIN_FILE = '1_Chap_Data_Real_Train.csv'
SYNTHETIC_FILE = '1_Chap_Data_Synthetic_WGANGP.csv'

In [3]:
#define directory of functions and actual directory
FUNCTIONS_DIR = FUNCTIONS_HOME + "PREPROCESSING"
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_DIR)

#import functions for univariate resemblance analisys
from preprocessing import DataPreProcessor

#change directory to actual directory
os.chdir(ACTUAL_DIR)

# from ydata_synthetic.synthesizers.regular import WGAN_GP
from ydata_synthetic.synthesizers.regular import RegularSynthesizer
from ydata_synthetic.synthesizers import ModelParameters, TrainParameters
print('Functions imported!!')

Functions imported!!

## Data Preprocessing

In [4]:
real_data = pd.read_csv(REAL_DATA_HOME + TRAIN_FILE)
categorical_columns = ['group']
for col in categorical_columns :
    real_data[col] = real_data[col].astype('category')
data_train = real_data
real_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,2.009493,0.084640,-0.020160,0.107037,0.857051,-0.048580,0.141517,0.137274
1,Group0,1.647881,0.285048,0.750705,-0.365256,0.594206,-0.094862,0.201428,-0.240859
2,Group0,0.045838,-0.301003,-0.007641,0.189160,1.875668,-0.152879,0.003445,0.012916
3,Group0,-1.626382,0.438629,-0.352224,-0.147169,-2.445341,0.362086,-0.132354,-0.016382
4,Group0,-0.244556,-0.781058,0.191160,0.637441,-2.766078,-1.110363,0.746589,0.140332
...,...,...,...,...,...,...,...,...,...
2712,Group0,0.048656,0.340805,0.146978,-0.077990,1.468295,-0.105885,0.037067,-0.001841
2713,Group0,-3.007362,-0.110868,-0.547719,-0.061449,-3.286850,-0.079093,-0.126217,0.165070
2714,Group0,0.481546,-0.118290,-0.159216,-0.046665,0.013795,0.235801,-0.128855,0.206748
2715,Group0,0.199530,0.371273,0.268324,0.670192,0.275167,-0.382674,0.076358,0.294886
2716,Group0,3.319253,0.852148,-1.115749,-0.142213,4.733011,1.221218,-0.466025,-0.221787

In [5]:
# data configuration
preprocessor = DataPreProcessor(data_train)
data_train = preprocessor.preprocess_train_data()
data_train

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4,group0,group1
0,0.473990,0.137505,-0.099886,0.260214,0.215366,0.011184,0.321453,0.602461,0.206383,-0.206383
1,0.385481,0.412195,1.414785,-1.538066,0.144523,-0.051958,0.482620,-1.491322,0.206383,-0.206383
2,-0.006639,-0.391078,-0.075289,0.572899,0.489904,-0.131111,-0.049971,-0.086129,0.206383,-0.206383
3,-0.415936,0.622701,-0.752359,-0.707691,-0.674698,0.571450,-0.415285,-0.248358,0.206383,-0.206383
4,-0.077717,-1.049067,0.315336,2.279751,-0.761143,-1.437393,1.949154,0.619394,0.206383,-0.206383
...,...,...,...,...,...,...,...,...,...,...
2712,-0.005949,0.488619,0.228523,-0.444286,0.380109,-0.066997,0.040473,-0.167841,0.206383,-0.206383
2713,-0.753948,-0.130468,-1.136487,-0.381308,-0.901502,-0.030446,-0.398775,0.756374,0.206383,-0.206383
2714,0.100006,-0.140642,-0.373118,-0.325015,-0.011909,0.399161,-0.405872,0.987149,0.206383,-0.206383
2715,0.030979,0.530379,0.466956,2.404453,0.058536,-0.444616,0.146170,1.475183,0.206383,-0.206383
2716,0.794570,1.189491,-2.252608,-0.688818,1.260018,1.743551,-1.312889,-1.385716,0.206383,-0.206383

## Train the Model

Next, lets define the neural network for generating synthetic data. We will be using a [GAN](https://www.wikiwand.com/en/Generative_adversarial_network) network that comprises of an generator and discriminator that tries to beat each other and in the process learns the vector embedding for the data. 

The model was taken from a [Github repository](https://github.com/ydataai/gan-playground) where it is used to generate synthetic data on credit card fraud data.

Next, lets define the training parameters for the GAN network.

In [6]:
# Training configuration
noise_dim = 128
dim = 128
batch_size = 500

log_step = 100
epochs = 300
learning_rate = 5e-4

beta_1 = 0.5
beta_2 = 0.9

models_dir = 'my_model_datasetA/'

data_dim = data_train.shape[1]
print('Shape of data: ', data_train.shape)
print('Number of columns: ', data_dim)

Shape of data:  (2717, 10)
Number of columns:  10

In [7]:
# Define model parameters using new API
model_args = ModelParameters(
    batch_size=batch_size,
    lr=learning_rate,
    betas=(beta_1, beta_2),
    noise_dim=noise_dim,
    layers_dim=dim,
    n_critic=2,  # Number of critic iterations per generator iteration
    gp_lambda=10.0  # Gradient penalty lambda for WGAN-GP
)

# Define training parameters
train_args = TrainParameters(
    epochs=epochs,
    sample_interval=log_step
)

print("Model parameters configured!")
print(f"Model: WGAN-GP")
print(f"Batch size: {batch_size}")
print(f"Learning rate: {learning_rate}")
print(f"Epochs: {epochs}")

Model parameters configured!
Model: WGAN-GP
Batch size: 500
Learning rate: 0.0005
Epochs: 300

Finally, let's run the training and see if the model is able to learn something.

In [8]:
!mkdir my_model_datasetA
!mkdir my_model_datasetA/gan
!mkdir my_model_datasetA/gan/saved

mkdir: my_model_datasetA: File exists
mkdir: my_model_datasetA/gan: File exists
mkdir: my_model_datasetA/gan/saved: File exists

In [9]:
# Training the WGAN-GP model using new API
print("Creating WGAN-GP synthesizer...")
synthesizer = RegularSynthesizer(
    modelname='wgangp',  # Use 'wgangp' for WGAN with Gradient Penalty
    model_parameters=model_args
)

# After preprocessing, all columns are numerical (categorical vars are one-hot encoded)
num_cols = list(data_train.columns)
cat_cols = []

print(f"Number of numerical columns: {len(num_cols)}")
print(f"Number of categorical columns: {len(cat_cols)}")

print("\nTraining the model...")
synthesizer.fit(
    data=data_train,
    train_arguments=train_args,
    num_cols=num_cols,
    cat_cols=cat_cols
)
print("Training completed!")

Creating WGAN-GP synthesizer...

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

Number of numerical columns: 10
Number of categorical columns: 0

Training the model...

  1%|▏         | 4/300 [00:00<00:39,  7.49it/s]

Epoch: 0 | disc_loss: 0.5167895555496216 | gen_loss: -0.0275475662201643
Epoch: 1 | disc_loss: 0.14125783741474152 | gen_loss: -0.013092548586428165
Epoch: 2 | disc_loss: 0.0823894664645195 | gen_loss: -0.0009077980066649616
Epoch: 3 | disc_loss: 0.06613792479038239 | gen_loss: -0.08003482967615128
Epoch: 4 | disc_loss: 0.15740710496902466 | gen_loss: 0.12569601833820343

  3%|▎         | 10/300 [00:00<00:20, 14.38it/s]

Epoch: 5 | disc_loss: 0.24285389482975006 | gen_loss: 0.07663559913635254
Epoch: 6 | disc_loss: -0.010618006810545921 | gen_loss: 0.005557493306696415
Epoch: 7 | disc_loss: -0.11159347742795944 | gen_loss: 0.14361423254013062
Epoch: 8 | disc_loss: 0.058691129088401794 | gen_loss: 0.021149083971977234
Epoch: 9 | disc_loss: -0.08140778541564941 | gen_loss: 0.0389493852853775

  5%|▍         | 14/300 [00:01<00:17, 16.60it/s]

Epoch: 10 | disc_loss: 0.23364467918872833 | gen_loss: -0.06889370828866959
Epoch: 11 | disc_loss: 0.09319768100976944 | gen_loss: 0.06330444663763046
Epoch: 12 | disc_loss: 0.32557573914527893 | gen_loss: 0.0066067217849195
Epoch: 13 | disc_loss: 0.18227823078632355 | gen_loss: -0.03540947660803795

  6%|▌         | 18/300 [00:01<00:16, 17.40it/s]

Epoch: 14 | disc_loss: 0.4729709327220917 | gen_loss: -0.15279440581798553
Epoch: 15 | disc_loss: 0.13492810726165771 | gen_loss: -0.07439851015806198
Epoch: 16 | disc_loss: -0.1005840003490448 | gen_loss: 0.06208448112010956
Epoch: 17 | disc_loss: 0.3689076900482178 | gen_loss: -0.14503537118434906

  7%|▋         | 20/300 [00:01<00:16, 17.06it/s]

Epoch: 18 | disc_loss: -0.005370832979679108 | gen_loss: -0.037901394069194794
Epoch: 19 | disc_loss: -0.08850786834955215 | gen_loss: 0.04472808167338371
Epoch: 20 | disc_loss: 0.0479716956615448 | gen_loss: 0.013825720176100731

  8%|▊         | 24/300 [00:01<00:17, 15.67it/s]

Epoch: 21 | disc_loss: -0.030745919793844223 | gen_loss: -0.02403542958199978
Epoch: 22 | disc_loss: 0.010740082710981369 | gen_loss: -0.16147677600383759
Epoch: 23 | disc_loss: 0.28556519746780396 | gen_loss: -0.057775869965553284
Epoch: 24 | disc_loss: -0.04151047021150589 | gen_loss: -0.03769350424408913

  9%|▉         | 28/300 [00:02<00:17, 15.18it/s]

Epoch: 25 | disc_loss: 0.07786055654287338 | gen_loss: -0.04297050088644028
Epoch: 26 | disc_loss: 0.1560347080230713 | gen_loss: -0.12821514904499054
Epoch: 27 | disc_loss: -0.047274865210056305 | gen_loss: -0.045397013425827026

 10%|█         | 30/300 [00:02<00:18, 14.61it/s]

Epoch: 28 | disc_loss: 1.3263866901397705 | gen_loss: -0.10967304557561874
Epoch: 29 | disc_loss: -0.16075757145881653 | gen_loss: 0.05225566774606705
Epoch: 30 | disc_loss: -0.07611863315105438 | gen_loss: -0.037854649126529694

 11%|█▏        | 34/300 [00:02<00:19, 13.69it/s]

Epoch: 31 | disc_loss: -0.0402899906039238 | gen_loss: -0.05825343355536461
Epoch: 32 | disc_loss: 0.0047291964292526245 | gen_loss: -0.060460664331912994
Epoch: 33 | disc_loss: -0.009021297097206116 | gen_loss: -0.03203269839286804

 12%|█▏        | 36/300 [00:02<00:20, 13.09it/s]

Epoch: 34 | disc_loss: 0.6601814031600952 | gen_loss: -0.16696619987487793
Epoch: 35 | disc_loss: -0.07237958163022995 | gen_loss: 0.08388318121433258
Epoch: 36 | disc_loss: 0.03525284677743912 | gen_loss: -0.043690841645002365

 13%|█▎        | 40/300 [00:02<00:20, 12.41it/s]

Epoch: 37 | disc_loss: -0.10197755694389343 | gen_loss: 2.5196068236255087e-05
Epoch: 38 | disc_loss: -0.04481341689825058 | gen_loss: -0.009437491185963154
Epoch: 39 | disc_loss: -0.04640652984380722 | gen_loss: -0.07888451218605042

 14%|█▍        | 42/300 [00:03<00:21, 12.10it/s]

Epoch: 40 | disc_loss: 1.437724232673645 | gen_loss: -0.1285535842180252
Epoch: 41 | disc_loss: 0.4604247212409973 | gen_loss: 0.004819480236619711
Epoch: 42 | disc_loss: -0.07314467430114746 | gen_loss: -0.019008124247193336

 15%|█▌        | 46/300 [00:03<00:21, 11.59it/s]

Epoch: 43 | disc_loss: 0.18087968230247498 | gen_loss: -0.06967834383249283
Epoch: 44 | disc_loss: -0.014912933111190796 | gen_loss: -0.0594407320022583
Epoch: 45 | disc_loss: 0.08550329506397247 | gen_loss: -0.12774866819381714

 16%|█▌        | 48/300 [00:03<00:22, 11.18it/s]

Epoch: 46 | disc_loss: -0.07073801755905151 | gen_loss: -0.025211257860064507
Epoch: 47 | disc_loss: 0.025192365050315857 | gen_loss: -0.06130142882466316
Epoch: 48 | disc_loss: -0.07504557073116302 | gen_loss: -0.04968549311161041

 17%|█▋        | 52/300 [00:04<00:22, 11.01it/s]

Epoch: 49 | disc_loss: 0.05913224816322327 | gen_loss: -0.11143331229686737
Epoch: 50 | disc_loss: -0.006075430661439896 | gen_loss: -0.11717985570430756
Epoch: 51 | disc_loss: 0.026252366602420807 | gen_loss: -0.20859430730342865

 18%|█▊        | 54/300 [00:04<00:23, 10.65it/s]

Epoch: 52 | disc_loss: 0.08145362883806229 | gen_loss: -0.22302106022834778
Epoch: 53 | disc_loss: 0.14262741804122925 | gen_loss: -0.27000001072883606
Epoch: 54 | disc_loss: 0.3482663929462433 | gen_loss: -0.0148754408583045

 19%|█▊        | 56/300 [00:04<00:23, 10.29it/s]

Epoch: 55 | disc_loss: 0.33757293224334717 | gen_loss: 0.05435914546251297
Epoch: 56 | disc_loss: 0.06823118776082993 | gen_loss: 0.005829749163240194

 20%|██        | 60/300 [00:04<00:24,  9.80it/s]

Epoch: 57 | disc_loss: -0.1019686684012413 | gen_loss: -0.012087210081517696
Epoch: 58 | disc_loss: -0.0025506503880023956 | gen_loss: -0.06725607812404633
Epoch: 59 | disc_loss: -0.023674942553043365 | gen_loss: -0.0937483087182045

 21%|██        | 62/300 [00:05<00:24,  9.65it/s]

Epoch: 60 | disc_loss: 0.15251530706882477 | gen_loss: -0.17031627893447876
Epoch: 61 | disc_loss: 0.011038271710276604 | gen_loss: -0.17682284116744995

 21%|██▏       | 64/300 [00:05<00:24,  9.59it/s]

Epoch: 62 | disc_loss: 0.0020262913312762976 | gen_loss: -0.17626510560512543
Epoch: 63 | disc_loss: 0.2533453106880188 | gen_loss: -0.027857841923832893

 22%|██▏       | 65/300 [00:05<00:26,  8.83it/s]

Epoch: 64 | disc_loss: 0.018516691401600838 | gen_loss: -0.22486211359500885
Epoch: 65 | disc_loss: 0.1075175330042839 | gen_loss: -0.2838914096355438

 23%|██▎       | 69/300 [00:05<00:24,  9.52it/s]

Epoch: 66 | disc_loss: 0.14644679427146912 | gen_loss: -0.3095646798610687
Epoch: 67 | disc_loss: -0.032555319368839264 | gen_loss: 0.04455946013331413
Epoch: 68 | disc_loss: -0.1291457861661911 | gen_loss: 0.08997049927711487

 24%|██▎       | 71/300 [00:06<00:25,  9.13it/s]

Epoch: 69 | disc_loss: -0.09367676079273224 | gen_loss: -0.045489516109228134
Epoch: 70 | disc_loss: 0.34869593381881714 | gen_loss: -0.12911729514598846

 24%|██▍       | 73/300 [00:06<00:25,  8.93it/s]

Epoch: 71 | disc_loss: 0.25580015778541565 | gen_loss: -0.1423712819814682
Epoch: 72 | disc_loss: 0.013188589364290237 | gen_loss: -0.16353872418403625

 25%|██▌       | 75/300 [00:06<00:24,  9.03it/s]

Epoch: 73 | disc_loss: 0.020732861012220383 | gen_loss: -0.18420034646987915
Epoch: 74 | disc_loss: 0.4876510500907898 | gen_loss: -0.16734305024147034

 26%|██▌       | 77/300 [00:06<00:25,  8.67it/s]

Epoch: 75 | disc_loss: 0.03358083963394165 | gen_loss: -0.21558630466461182
Epoch: 76 | disc_loss: 0.03963559493422508 | gen_loss: -0.21360337734222412

 27%|██▋       | 80/300 [00:07<00:23,  9.48it/s]

Epoch: 77 | disc_loss: 0.25389349460601807 | gen_loss: -0.21590599417686462
Epoch: 78 | disc_loss: 0.23046010732650757 | gen_loss: -0.1626189798116684
Epoch: 79 | disc_loss: 0.08180685341358185 | gen_loss: -0.18035568296909332

 27%|██▋       | 82/300 [00:07<00:23,  9.17it/s]

Epoch: 80 | disc_loss: 0.014526628889143467 | gen_loss: -0.17948578298091888
Epoch: 81 | disc_loss: 0.010655936785042286 | gen_loss: -0.17537568509578705

 28%|██▊       | 84/300 [00:07<00:23,  9.07it/s]

Epoch: 82 | disc_loss: 0.012333720922470093 | gen_loss: -0.1784881055355072
Epoch: 83 | disc_loss: 0.6158802509307861 | gen_loss: -0.16786931455135345

 29%|██▊       | 86/300 [00:07<00:24,  8.70it/s]

Epoch: 84 | disc_loss: 0.06400945037603378 | gen_loss: -0.19619442522525787
Epoch: 85 | disc_loss: 0.5210669636726379 | gen_loss: -0.1749083697795868

 29%|██▉       | 88/300 [00:08<00:24,  8.53it/s]

Epoch: 86 | disc_loss: 0.21040724217891693 | gen_loss: -0.20901387929916382
Epoch: 87 | disc_loss: 0.2019951045513153 | gen_loss: -0.2225063145160675

 30%|███       | 90/300 [00:08<00:24,  8.44it/s]

Epoch: 88 | disc_loss: 0.19114868342876434 | gen_loss: -0.19834600389003754
Epoch: 89 | disc_loss: 0.04732995480298996 | gen_loss: -0.24965877830982208

 31%|███       | 92/300 [00:08<00:26,  7.94it/s]

Epoch: 90 | disc_loss: 0.29855114221572876 | gen_loss: -0.16199365258216858
Epoch: 91 | disc_loss: 0.13559332489967346 | gen_loss: -0.21087509393692017

 31%|███▏      | 94/300 [00:08<00:26,  7.83it/s]

Epoch: 92 | disc_loss: 0.20797336101531982 | gen_loss: -0.23290303349494934
Epoch: 93 | disc_loss: 1.9920541048049927 | gen_loss: -0.1918613761663437

 32%|███▏      | 96/300 [00:09<00:27,  7.51it/s]

Epoch: 94 | disc_loss: 0.03759065270423889 | gen_loss: -0.1830967217683792
Epoch: 95 | disc_loss: 0.013371475972235203 | gen_loss: -0.17586050927639008

 33%|███▎      | 98/300 [00:09<00:26,  7.67it/s]

Epoch: 96 | disc_loss: 0.02426275983452797 | gen_loss: -0.20758135616779327
Epoch: 97 | disc_loss: 0.09982094913721085 | gen_loss: -0.18580810725688934

 33%|███▎      | 100/300 [00:09<00:26,  7.48it/s]

Epoch: 98 | disc_loss: 0.006943380925804377 | gen_loss: -0.16699419915676117
Epoch: 99 | disc_loss: 0.031847380101680756 | gen_loss: -0.1955164074897766

 34%|███▍      | 102/300 [00:09<00:26,  7.42it/s]

Epoch: 100 | disc_loss: 0.011181815527379513 | gen_loss: -0.19654637575149536
Epoch: 101 | disc_loss: 0.01164827961474657 | gen_loss: -0.1863309144973755

 35%|███▍      | 104/300 [00:10<00:24,  7.96it/s]

Epoch: 102 | disc_loss: 2.3626620769500732 | gen_loss: -0.18225528299808502
Epoch: 103 | disc_loss: 0.2918391227722168 | gen_loss: -0.16928726434707642

 35%|███▌      | 106/300 [00:10<00:24,  8.04it/s]

Epoch: 104 | disc_loss: 0.01914912275969982 | gen_loss: -0.1709374189376831
Epoch: 105 | disc_loss: 0.1188109964132309 | gen_loss: -0.1623772233724594

 36%|███▌      | 108/300 [00:10<00:24,  7.73it/s]

Epoch: 106 | disc_loss: 0.8731986284255981 | gen_loss: -0.15932504832744598
Epoch: 107 | disc_loss: 0.08141935616731644 | gen_loss: -0.1733889877796173

 37%|███▋      | 110/300 [00:10<00:23,  8.02it/s]

Epoch: 108 | disc_loss: 0.39877849817276 | gen_loss: -0.16137005388736725
Epoch: 109 | disc_loss: 0.04952724650502205 | gen_loss: -0.1955094039440155

 37%|███▋      | 112/300 [00:11<00:22,  8.21it/s]

Epoch: 110 | disc_loss: 0.010002914816141129 | gen_loss: -0.1498679518699646
Epoch: 111 | disc_loss: 0.041136834770441055 | gen_loss: -0.2267095148563385

 38%|███▊      | 114/300 [00:11<00:22,  8.24it/s]

Epoch: 112 | disc_loss: 0.6852774620056152 | gen_loss: -0.15971510112285614
Epoch: 113 | disc_loss: 0.18773490190505981 | gen_loss: -0.1765466332435608

 39%|███▊      | 116/300 [00:11<00:24,  7.57it/s]

Epoch: 114 | disc_loss: 0.04439768195152283 | gen_loss: -0.1632269322872162
Epoch: 115 | disc_loss: 0.03363175690174103 | gen_loss: -0.15306000411510468

 39%|███▉      | 118/300 [00:11<00:22,  8.03it/s]

Epoch: 116 | disc_loss: 0.35164326429367065 | gen_loss: -0.15166665613651276
Epoch: 117 | disc_loss: 0.04541454836726189 | gen_loss: -0.16124123334884644

 40%|████      | 120/300 [00:12<00:22,  7.96it/s]

Epoch: 118 | disc_loss: 0.5218220353126526 | gen_loss: -0.04841316118836403
Epoch: 119 | disc_loss: 0.04702404513955116 | gen_loss: -0.16927537322044373

 41%|████      | 122/300 [00:12<00:21,  8.24it/s]

Epoch: 120 | disc_loss: 0.06734421849250793 | gen_loss: -0.13921844959259033
Epoch: 121 | disc_loss: 0.1860893964767456 | gen_loss: -0.11651670932769775

 41%|████▏     | 124/300 [00:12<00:22,  7.69it/s]

Epoch: 122 | disc_loss: 0.27061158418655396 | gen_loss: -0.1422485113143921
Epoch: 123 | disc_loss: 0.019071202725172043 | gen_loss: -0.12403331696987152

 42%|████▏     | 126/300 [00:12<00:22,  7.73it/s]

Epoch: 124 | disc_loss: 0.03842446953058243 | gen_loss: -0.11379872262477875
Epoch: 125 | disc_loss: 0.21755486726760864 | gen_loss: -0.09865189343690872

 43%|████▎     | 128/300 [00:13<00:21,  8.04it/s]

Epoch: 126 | disc_loss: 0.07772441953420639 | gen_loss: -0.0980757549405098
Epoch: 127 | disc_loss: 0.21460570394992828 | gen_loss: -0.08661585301160812

 43%|████▎     | 130/300 [00:13<00:19,  8.54it/s]

Epoch: 128 | disc_loss: 0.03069380298256874 | gen_loss: -0.07911042124032974
Epoch: 129 | disc_loss: 0.07273593544960022 | gen_loss: -0.09934242069721222

 44%|████▍     | 132/300 [00:13<00:19,  8.68it/s]

Epoch: 130 | disc_loss: 0.6332449316978455 | gen_loss: 0.002167938742786646
Epoch: 131 | disc_loss: 1.1050190925598145 | gen_loss: -0.08066226541996002

 45%|████▍     | 134/300 [00:13<00:18,  9.09it/s]

Epoch: 132 | disc_loss: 0.2972428798675537 | gen_loss: -0.06920229643583298
Epoch: 133 | disc_loss: 0.026968665421009064 | gen_loss: -0.056881967931985855

 45%|████▌     | 136/300 [00:14<00:18,  8.84it/s]

Epoch: 134 | disc_loss: 0.13443879783153534 | gen_loss: -0.05574435368180275
Epoch: 135 | disc_loss: 0.07901040464639664 | gen_loss: -0.06992277503013611

 46%|████▌     | 138/300 [00:14<00:17,  9.13it/s]

Epoch: 136 | disc_loss: 0.03419432044029236 | gen_loss: -0.07150929421186447
Epoch: 137 | disc_loss: 0.016093414276838303 | gen_loss: -0.027190525084733963
Epoch: 138 | disc_loss: 0.02989300526678562 | gen_loss: -0.025574658066034317

 47%|████▋     | 141/300 [00:14<00:16,  9.77it/s]

Epoch: 139 | disc_loss: 1.3861602544784546 | gen_loss: -0.024073872715234756
Epoch: 140 | disc_loss: 0.47486749291419983 | gen_loss: -0.036162156611680984

 48%|████▊     | 143/300 [00:14<00:16,  9.79it/s]

Epoch: 141 | disc_loss: 0.17868806421756744 | gen_loss: -0.046217963099479675
Epoch: 142 | disc_loss: 0.029036296531558037 | gen_loss: -0.0574474111199379
Epoch: 143 | disc_loss: 0.10214489698410034 | gen_loss: -0.04021136835217476

 49%|████▊     | 146/300 [00:15<00:15,  9.66it/s]

Epoch: 144 | disc_loss: 0.018173277378082275 | gen_loss: -0.03654447942972183
Epoch: 145 | disc_loss: 0.016718801110982895 | gen_loss: -0.044757179915905

 49%|████▉     | 148/300 [00:15<00:15, 10.08it/s]

Epoch: 146 | disc_loss: 0.1231401339173317 | gen_loss: -0.026442524045705795
Epoch: 147 | disc_loss: 0.3483201563358307 | gen_loss: -0.018661247566342354
Epoch: 148 | disc_loss: 0.16892796754837036 | gen_loss: -0.013744037598371506

 51%|█████     | 152/300 [00:15<00:13, 10.78it/s]

Epoch: 149 | disc_loss: 0.0220085009932518 | gen_loss: -0.006731329020112753
Epoch: 150 | disc_loss: 0.011244300752878189 | gen_loss: -0.01000114344060421
Epoch: 151 | disc_loss: 0.01805691421031952 | gen_loss: -0.012686784379184246

 51%|█████▏    | 154/300 [00:15<00:13, 11.11it/s]

Epoch: 152 | disc_loss: 0.05432472005486488 | gen_loss: 0.001192610478028655
Epoch: 153 | disc_loss: 0.08052480220794678 | gen_loss: 0.011782434768974781
Epoch: 154 | disc_loss: 0.08620163798332214 | gen_loss: 0.010052896104753017

 53%|█████▎    | 158/300 [00:16<00:12, 10.98it/s]

Epoch: 155 | disc_loss: 0.16044428944587708 | gen_loss: 0.049661535769701004
Epoch: 156 | disc_loss: 1.6818876266479492 | gen_loss: 0.0424104742705822
Epoch: 157 | disc_loss: 0.6318323612213135 | gen_loss: 0.030840342864394188

 53%|█████▎    | 160/300 [00:16<00:13, 10.65it/s]

Epoch: 158 | disc_loss: 0.0227425005286932 | gen_loss: 0.02254520356655121
Epoch: 159 | disc_loss: 0.03645186871290207 | gen_loss: 0.018184848129749298
Epoch: 160 | disc_loss: 0.11181872338056564 | gen_loss: 0.02963016927242279

 55%|█████▍    | 164/300 [00:16<00:12, 10.66it/s]

Epoch: 161 | disc_loss: 0.01994776353240013 | gen_loss: 0.02830180525779724
Epoch: 162 | disc_loss: 0.6774649620056152 | gen_loss: 0.024069057777523994
Epoch: 163 | disc_loss: 0.027466371655464172 | gen_loss: 0.02114914357662201

 55%|█████▌    | 166/300 [00:16<00:12, 11.06it/s]

Epoch: 164 | disc_loss: 0.15309977531433105 | gen_loss: 0.025516806170344353
Epoch: 165 | disc_loss: 0.018899893388152122 | gen_loss: 0.023243481293320656
Epoch: 166 | disc_loss: 0.016954202204942703 | gen_loss: 0.007188842631876469

 57%|█████▋    | 170/300 [00:17<00:12, 10.73it/s]

Epoch: 167 | disc_loss: 0.10399793088436127 | gen_loss: 0.09557731449604034
Epoch: 168 | disc_loss: 0.24082183837890625 | gen_loss: 0.051861781626939774
Epoch: 169 | disc_loss: 0.1329723745584488 | gen_loss: 0.05435073375701904

 57%|█████▋    | 172/300 [00:17<00:11, 10.94it/s]

Epoch: 170 | disc_loss: 0.030719053000211716 | gen_loss: 0.037414614111185074
Epoch: 171 | disc_loss: 0.03302473574876785 | gen_loss: 0.05936923250555992
Epoch: 172 | disc_loss: 0.021953407675027847 | gen_loss: 0.05619528144598007

 59%|█████▊    | 176/300 [00:17<00:11, 10.54it/s]

Epoch: 173 | disc_loss: 0.20896437764167786 | gen_loss: 0.050312407314777374
Epoch: 174 | disc_loss: 0.04054442048072815 | gen_loss: 0.0569925382733345
Epoch: 175 | disc_loss: 0.22467321157455444 | gen_loss: 0.06734289228916168

 59%|█████▉    | 178/300 [00:17<00:11, 10.64it/s]

Epoch: 176 | disc_loss: 0.013539403676986694 | gen_loss: 0.0754375159740448
Epoch: 177 | disc_loss: 0.10890909284353256 | gen_loss: 0.08247207850217819
Epoch: 178 | disc_loss: 0.010364966467022896 | gen_loss: 0.08555082976818085

 61%|██████    | 182/300 [00:18<00:10, 10.79it/s]

Epoch: 179 | disc_loss: 0.20205815136432648 | gen_loss: 0.0773112028837204
Epoch: 180 | disc_loss: 0.011259672231972218 | gen_loss: 0.061159610748291016
Epoch: 181 | disc_loss: 0.07203592360019684 | gen_loss: 0.05448329076170921

 61%|██████▏   | 184/300 [00:18<00:10, 10.67it/s]

Epoch: 182 | disc_loss: 0.46660855412483215 | gen_loss: 0.042202744632959366
Epoch: 183 | disc_loss: 0.4639057219028473 | gen_loss: 0.07260039448738098
Epoch: 184 | disc_loss: 0.06055315211415291 | gen_loss: 0.07192777842283249

 63%|██████▎   | 188/300 [00:18<00:10, 10.79it/s]

Epoch: 185 | disc_loss: 0.024089068174362183 | gen_loss: 0.06414303928613663
Epoch: 186 | disc_loss: 0.025404853746294975 | gen_loss: 0.06911100447177887
Epoch: 187 | disc_loss: 0.168680801987648 | gen_loss: 0.07383926212787628

 63%|██████▎   | 190/300 [00:19<00:10, 10.84it/s]

Epoch: 188 | disc_loss: 0.9668591618537903 | gen_loss: 0.07702436298131943
Epoch: 189 | disc_loss: 0.030309518799185753 | gen_loss: 0.08092056959867477
Epoch: 190 | disc_loss: -0.004300895147025585 | gen_loss: 0.08073443174362183

 65%|██████▍   | 194/300 [00:19<00:09, 10.65it/s]

Epoch: 191 | disc_loss: 0.10563358664512634 | gen_loss: 0.11307577788829803
Epoch: 192 | disc_loss: 0.02073804847896099 | gen_loss: 0.10082703083753586
Epoch: 193 | disc_loss: 0.2747681736946106 | gen_loss: 0.0820397287607193

 65%|██████▌   | 196/300 [00:19<00:09, 10.44it/s]

Epoch: 194 | disc_loss: 0.012693705968558788 | gen_loss: 0.08785533159971237
Epoch: 195 | disc_loss: 0.1539500206708908 | gen_loss: 0.08019182085990906
Epoch: 196 | disc_loss: 0.7770130634307861 | gen_loss: 0.08382637798786163

 66%|██████▌   | 198/300 [00:19<00:10, 10.14it/s]

Epoch: 197 | disc_loss: 0.048593513667583466 | gen_loss: 0.0874997079372406
Epoch: 198 | disc_loss: -0.005425472278147936 | gen_loss: 0.08394721895456314

 67%|██████▋   | 201/300 [00:20<00:10,  9.67it/s]

Epoch: 199 | disc_loss: -0.01030002161860466 | gen_loss: 0.07556155323982239
Epoch: 200 | disc_loss: 0.0063873836770653725 | gen_loss: 0.0652754008769989

 68%|██████▊   | 203/300 [00:20<00:10,  9.29it/s]

Epoch: 201 | disc_loss: 0.03363332897424698 | gen_loss: 0.05064743384718895
Epoch: 202 | disc_loss: 0.0019679092802107334 | gen_loss: 0.05800500512123108

 68%|██████▊   | 205/300 [00:20<00:10,  8.81it/s]

Epoch: 203 | disc_loss: 0.11847233772277832 | gen_loss: 0.07183392345905304
Epoch: 204 | disc_loss: 1.0178170204162598 | gen_loss: 0.08015187084674835

 69%|██████▉   | 207/300 [00:20<00:10,  8.60it/s]

Epoch: 205 | disc_loss: 0.15717089176177979 | gen_loss: 0.04615351930260658
Epoch: 206 | disc_loss: 0.03943917527794838 | gen_loss: 0.03248041495680809

 70%|██████▉   | 209/300 [00:21<00:10,  8.87it/s]

Epoch: 207 | disc_loss: 0.26848477125167847 | gen_loss: 0.04327482730150223
Epoch: 208 | disc_loss: 0.055130280554294586 | gen_loss: 0.0520036444067955

 70%|███████   | 211/300 [00:21<00:09,  9.18it/s]

Epoch: 209 | disc_loss: 0.18845859169960022 | gen_loss: 0.0487203523516655
Epoch: 210 | disc_loss: 0.0942908376455307 | gen_loss: 0.050992973148822784

 71%|███████   | 213/300 [00:21<00:09,  9.10it/s]

Epoch: 211 | disc_loss: 0.21339011192321777 | gen_loss: 0.04707253351807594
Epoch: 212 | disc_loss: 0.0966833159327507 | gen_loss: 0.06275662779808044

 72%|███████▏  | 215/300 [00:21<00:09,  8.51it/s]

Epoch: 213 | disc_loss: 0.023002896457910538 | gen_loss: 0.04807835444808006
Epoch: 214 | disc_loss: 0.012346609495580196 | gen_loss: 0.054646074771881104

 72%|███████▏  | 217/300 [00:22<00:09,  8.59it/s]

Epoch: 215 | disc_loss: 0.8508268594741821 | gen_loss: 0.062210939824581146
Epoch: 216 | disc_loss: 0.06429614126682281 | gen_loss: 0.06178116425871849

 73%|███████▎  | 219/300 [00:22<00:09,  8.57it/s]

Epoch: 217 | disc_loss: 0.6087468266487122 | gen_loss: 0.05194642022252083
Epoch: 218 | disc_loss: 0.027043327689170837 | gen_loss: 0.05087417736649513

 74%|███████▎  | 221/300 [00:22<00:08,  8.90it/s]

Epoch: 219 | disc_loss: 0.07549846172332764 | gen_loss: 0.04926304891705513
Epoch: 220 | disc_loss: 0.010262342169880867 | gen_loss: 0.04723433777689934

 74%|███████▍  | 223/300 [00:22<00:08,  8.69it/s]

Epoch: 221 | disc_loss: 0.012425445951521397 | gen_loss: 0.052213262766599655
Epoch: 222 | disc_loss: 0.11319030076265335 | gen_loss: 0.06851285696029663

 75%|███████▌  | 225/300 [00:22<00:08,  8.67it/s]

Epoch: 223 | disc_loss: 0.004948991350829601 | gen_loss: 0.06875579059123993
Epoch: 224 | disc_loss: 0.008291859179735184 | gen_loss: 0.07595927268266678

 76%|███████▌  | 227/300 [00:23<00:08,  8.36it/s]

Epoch: 225 | disc_loss: 0.04908657819032669 | gen_loss: 0.027270400896668434
Epoch: 226 | disc_loss: 0.03987693041563034 | gen_loss: 0.051849860697984695

 76%|███████▋  | 229/300 [00:23<00:08,  8.00it/s]

Epoch: 227 | disc_loss: 0.03149813413619995 | gen_loss: 0.03937297686934471
Epoch: 228 | disc_loss: 0.02562963217496872 | gen_loss: 0.03943789005279541

 77%|███████▋  | 231/300 [00:23<00:09,  7.57it/s]

Epoch: 229 | disc_loss: 0.013222258538007736 | gen_loss: 0.027014493942260742
Epoch: 230 | disc_loss: 0.8174400925636292 | gen_loss: 0.046051640063524246

 78%|███████▊  | 233/300 [00:23<00:07,  8.58it/s]

Epoch: 231 | disc_loss: 0.1346631646156311 | gen_loss: 0.07711605727672577
Epoch: 232 | disc_loss: 0.011686014011502266 | gen_loss: 0.06995761394500732

 78%|███████▊  | 235/300 [00:24<00:07,  8.76it/s]

Epoch: 233 | disc_loss: 0.01578916609287262 | gen_loss: 0.07228051871061325
Epoch: 234 | disc_loss: 0.045060835778713226 | gen_loss: 0.08385971188545227

 79%|███████▉  | 237/300 [00:24<00:07,  8.03it/s]

Epoch: 235 | disc_loss: 0.10304092615842819 | gen_loss: 0.08417579531669617
Epoch: 236 | disc_loss: 0.06459712982177734 | gen_loss: 0.09983298182487488

 80%|███████▉  | 239/300 [00:24<00:07,  8.08it/s]

Epoch: 237 | disc_loss: 0.03251161798834801 | gen_loss: 0.0890452116727829
Epoch: 238 | disc_loss: 0.03161679953336716 | gen_loss: 0.0866038128733635

 80%|████████  | 241/300 [00:25<00:07,  7.60it/s]

Epoch: 239 | disc_loss: 0.016990825533866882 | gen_loss: 0.09294912964105606
Epoch: 240 | disc_loss: 0.008746049366891384 | gen_loss: 0.09590106457471848

 81%|████████  | 243/300 [00:25<00:07,  7.69it/s]

Epoch: 241 | disc_loss: 0.03728973865509033 | gen_loss: 0.10931946337223053
Epoch: 242 | disc_loss: 0.00616477569565177 | gen_loss: 0.11649710685014725

 82%|████████▏ | 245/300 [00:25<00:07,  7.36it/s]

Epoch: 243 | disc_loss: 0.43537604808807373 | gen_loss: 0.11230962723493576
Epoch: 244 | disc_loss: 0.06698375940322876 | gen_loss: 0.12180867791175842

 82%|████████▏ | 247/300 [00:25<00:06,  7.59it/s]

Epoch: 245 | disc_loss: 0.16011033952236176 | gen_loss: 0.09058630466461182
Epoch: 246 | disc_loss: 0.20960132777690887 | gen_loss: 0.09943123906850815

 83%|████████▎ | 249/300 [00:26<00:06,  7.85it/s]

Epoch: 247 | disc_loss: 0.05350542068481445 | gen_loss: 0.11302448809146881
Epoch: 248 | disc_loss: 0.36196473240852356 | gen_loss: 0.10176977515220642

 84%|████████▎ | 251/300 [00:26<00:05,  8.33it/s]

Epoch: 249 | disc_loss: 0.037921562790870667 | gen_loss: 0.11494218558073044
Epoch: 250 | disc_loss: 0.08168783783912659 | gen_loss: 0.11352726072072983

 84%|████████▍ | 253/300 [00:26<00:05,  8.72it/s]

Epoch: 251 | disc_loss: 0.23625561594963074 | gen_loss: 0.09697011858224869
Epoch: 252 | disc_loss: 0.06979692727327347 | gen_loss: 0.10471244156360626

 85%|████████▌ | 255/300 [00:26<00:05,  8.67it/s]

Epoch: 253 | disc_loss: 0.0049868132919073105 | gen_loss: 0.11357693374156952
Epoch: 254 | disc_loss: 0.2622109353542328 | gen_loss: 0.10578417778015137

 86%|████████▌ | 257/300 [00:26<00:04,  8.63it/s]

Epoch: 255 | disc_loss: 0.06501501798629761 | gen_loss: 0.10061012953519821
Epoch: 256 | disc_loss: 0.01887298934161663 | gen_loss: 0.1343519240617752

 86%|████████▌ | 258/300 [00:27<00:04,  8.92it/s]

Epoch: 257 | disc_loss: 0.14920812845230103 | gen_loss: 0.13333871960639954
Epoch: 258 | disc_loss: 0.023960646241903305 | gen_loss: 0.13534775376319885

 87%|████████▋ | 261/300 [00:27<00:04,  8.81it/s]

Epoch: 259 | disc_loss: 0.18984824419021606 | gen_loss: 0.13979722559452057
Epoch: 260 | disc_loss: 0.2389426827430725 | gen_loss: 0.14567682147026062

 88%|████████▊ | 263/300 [00:27<00:04,  8.47it/s]

Epoch: 261 | disc_loss: 0.020159481093287468 | gen_loss: 0.12816296517848969
Epoch: 262 | disc_loss: 0.054438091814517975 | gen_loss: 0.13219381868839264

 88%|████████▊ | 265/300 [00:27<00:04,  8.59it/s]

Epoch: 263 | disc_loss: 0.17699992656707764 | gen_loss: 0.1439145803451538
Epoch: 264 | disc_loss: 0.26133209466934204 | gen_loss: 0.14217083156108856

 89%|████████▉ | 267/300 [00:28<00:03,  8.95it/s]

Epoch: 265 | disc_loss: 0.1188969537615776 | gen_loss: 0.13943910598754883
Epoch: 266 | disc_loss: 0.11381845921278 | gen_loss: 0.1462339460849762

 90%|████████▉ | 269/300 [00:28<00:03,  8.25it/s]

Epoch: 267 | disc_loss: 8.446479114354588e-06 | gen_loss: 0.1482982635498047
Epoch: 268 | disc_loss: 0.004178689327090979 | gen_loss: 0.10662396252155304

 90%|█████████ | 271/300 [00:28<00:03,  8.28it/s]

Epoch: 269 | disc_loss: 0.0885562002658844 | gen_loss: 0.10938874632120132
Epoch: 270 | disc_loss: 0.041362449526786804 | gen_loss: 0.13252805173397064

 91%|█████████ | 273/300 [00:28<00:03,  8.12it/s]

Epoch: 271 | disc_loss: 0.003582943929359317 | gen_loss: 0.11006934940814972
Epoch: 272 | disc_loss: 0.4909523129463196 | gen_loss: 0.11746115237474442

 92%|█████████▏| 275/300 [00:29<00:02,  8.36it/s]

Epoch: 273 | disc_loss: 0.015544818714261055 | gen_loss: 0.11974611133337021
Epoch: 274 | disc_loss: 0.08639741688966751 | gen_loss: 0.10745299607515335

 93%|█████████▎| 278/300 [00:29<00:02,  9.53it/s]

Epoch: 275 | disc_loss: 0.00438182707875967 | gen_loss: 0.0933665931224823
Epoch: 276 | disc_loss: 0.06387098133563995 | gen_loss: 0.10543972998857498
Epoch: 277 | disc_loss: 0.015196869149804115 | gen_loss: 0.08498749881982803

 94%|█████████▎| 281/300 [00:29<00:01, 10.25it/s]

Epoch: 278 | disc_loss: 0.013533253222703934 | gen_loss: 0.07070497423410416
Epoch: 279 | disc_loss: 0.3386288285255432 | gen_loss: 0.07593166828155518
Epoch: 280 | disc_loss: 0.29549145698547363 | gen_loss: 0.05814425274729729

 94%|█████████▍| 283/300 [00:29<00:01, 10.56it/s]

Epoch: 281 | disc_loss: 0.05195808783173561 | gen_loss: 0.06511277705430984
Epoch: 282 | disc_loss: 0.03182163089513779 | gen_loss: 0.07684725522994995
Epoch: 283 | disc_loss: 0.4873383045196533 | gen_loss: 0.09100610017776489

 96%|█████████▌| 287/300 [00:30<00:01, 10.52it/s]

Epoch: 284 | disc_loss: 0.0067293038591742516 | gen_loss: 0.09169917553663254
Epoch: 285 | disc_loss: 0.018734170123934746 | gen_loss: 0.10450750589370728
Epoch: 286 | disc_loss: 0.012074131518602371 | gen_loss: 0.08644483983516693

 96%|█████████▋| 289/300 [00:30<00:01, 10.19it/s]

Epoch: 287 | disc_loss: 0.6532763242721558 | gen_loss: 0.09978846460580826
Epoch: 288 | disc_loss: 0.06727466732263565 | gen_loss: 0.1049688458442688

 97%|█████████▋| 291/300 [00:30<00:00,  9.99it/s]

Epoch: 289 | disc_loss: 0.021107349544763565 | gen_loss: 0.08820395171642303
Epoch: 290 | disc_loss: 0.015457944944500923 | gen_loss: 0.09718496352434158

 98%|█████████▊| 293/300 [00:30<00:00,  9.32it/s]

Epoch: 291 | disc_loss: 0.24858666956424713 | gen_loss: 0.1033012717962265
Epoch: 292 | disc_loss: 0.03765914961695671 | gen_loss: 0.08202855288982391

 98%|█████████▊| 295/300 [00:31<00:00,  9.55it/s]

Epoch: 293 | disc_loss: 0.006768973544239998 | gen_loss: 0.07649662345647812
Epoch: 294 | disc_loss: 0.07769018411636353 | gen_loss: 0.10470188409090042

 99%|█████████▉| 297/300 [00:31<00:00,  9.30it/s]

Epoch: 295 | disc_loss: 0.07883089035749435 | gen_loss: 0.0990782305598259
Epoch: 296 | disc_loss: 0.01657206378877163 | gen_loss: 0.08755761384963989

100%|█████████▉| 299/300 [00:31<00:00,  9.38it/s]

Epoch: 297 | disc_loss: 0.01471632719039917 | gen_loss: 0.0759827271103859
Epoch: 298 | disc_loss: 0.7154006958007812 | gen_loss: 0.1004749983549118

100%|██████████| 300/300 [00:31<00:00,  9.49it/s]

Epoch: 299 | disc_loss: 0.0619833767414093 | gen_loss: 0.10857997834682465
Training completed!

In [10]:
synthesizer.generator.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(500, 128)]              0

 dense (Dense)               (500, 128)                16512

 dense_1 (Dense)             (500, 256)                33024

 dense_2 (Dense)             (500, 512)                131584

 dense_3 (Dense)             (500, 10)                 5130

=================================================================
Total params: 186250 (727.54 KB)
Trainable params: 186250 (727.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [11]:
synthesizer.critic.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_2 (InputLayer)        [(500, 10)]               0

 dense_4 (Dense)             (500, 512)                5632

 dropout (Dropout)           (500, 512)                0

 dense_5 (Dense)             (500, 256)                131328

 dropout_1 (Dropout)         (500, 256)                0

 dense_6 (Dense)             (500, 128)                32896

 dense_7 (Dense)             (500, 1)                  129

=================================================================
Total params: 169985 (664.00 KB)
Trainable params: 169985 (664.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

## Generate data

In [12]:
size = len(data_train)
print(f"Generating {size} synthetic samples...")

# Generate synthetic data using new API
generated_samples = synthesizer.sample(n_samples=size)
generated_samples.columns = data_train.columns

print(f"Generated data shape: {generated_samples.shape}")
generated_samples

Generating 2717 synthetic samples...

Synthetic data generation: 100%|██████████| 6/6 [00:00<00:00, 150.52it/s]

Generated data shape: (3000, 10)

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4,group0,group1
0,-2.108581,-0.725906,-1.885004,-1.880190,-1.188501,-0.242911,-2.130230,-3.205923,-2.139716,1.011624
1,-1.704843,-0.213173,-2.256733,-1.944650,-0.684592,-0.148036,-2.106706,-2.889154,-1.304963,0.045494
2,-2.125141,-0.825191,-1.681782,-1.940694,-1.313997,-0.021351,-1.962547,-3.058310,-2.623789,1.570920
3,-1.546271,-0.125571,-2.082254,-1.897275,-0.599286,0.077637,-2.084931,-2.711187,-1.304448,0.111302
4,-1.166978,0.264708,-1.967464,-1.701794,-0.117048,0.571493,-1.664608,-2.055417,-0.796451,-0.293525
...,...,...,...,...,...,...,...,...,...,...
2995,-1.724661,-0.372880,-1.804269,-1.888091,-0.843158,0.288473,-1.974008,-2.767337,-2.018383,0.955158
2996,-1.693089,-0.293187,-1.807616,-1.810659,-0.795127,0.044171,-2.089338,-2.818455,-1.614474,0.543691
2997,-2.195131,-0.757494,-1.884931,-1.939381,-1.242253,-0.304875,-2.170465,-3.270792,-2.273406,1.157572
2998,-1.936519,-0.519760,-1.956186,-1.868494,-0.994470,-0.158999,-2.152917,-3.095167,-1.836972,0.694162
2999,-1.439608,-0.012767,-2.096111,-1.855614,-0.448523,0.235031,-2.042590,-2.602203,-1.235569,0.067084

## Transform and process generated data

In [13]:
import importlib
import sys
FUNCTIONS_DIR = FUNCTIONS_HOME + "PREPROCESSING"
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_DIR)
# 从 sys.modules 中移除旧模块
if 'preprocessing' in sys.modules:
    del sys.modules['preprocessing']

# 重新导入
from preprocessing import DataPreProcessor
os.chdir(ACTUAL_DIR)
# 重新创建 preprocessor
preprocessor = DataPreProcessor(real_data)
data_train = preprocessor.preprocess_train_data()

print("✓ 模块已重新导入")

✓ 模块已重新导入

In [14]:
synthetic_data = preprocessor.transform_data(generated_samples)
synthetic_data = synthetic_data[0:len(real_data)]
synthetic_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,-8.541844,-0.545287,-0.928663,-0.455110,-4.351696,-0.234827,-0.769859,-0.550513
1,Group0,-6.892333,-0.171208,-1.117848,-0.472040,-2.482052,-0.165285,-0.761114,-0.493305
2,Group0,-8.609503,-0.617723,-0.825237,-0.471001,-4.817324,-0.072427,-0.707525,-0.523854
3,Group0,-6.244475,-0.107295,-1.029050,-0.459597,-2.165540,0.000130,-0.753020,-0.461165
4,Group0,-4.694835,0.177444,-0.970630,-0.408257,-0.376301,0.362118,-0.596771,-0.342734
...,...,...,...,...,...,...,...,...,...
2712,Group0,-5.952104,-0.110032,-0.914333,-0.425598,-1.995470,0.118183,-0.695510,-0.433784
2713,Group0,-7.202361,-0.255103,-1.023678,-0.456831,-2.909712,-0.190980,-0.777772,-0.505518
2714,Group0,-5.041869,0.095305,-0.988946,-0.426792,-0.824161,0.251926,-0.629764,-0.374986
2715,Group0,-6.180864,-0.117613,-0.936792,-0.430850,-2.062372,0.121498,-0.726012,-0.449142
2716,Group0,-6.411942,-0.133883,-0.967993,-0.442769,-2.359679,-0.063674,-0.736019,-0.460374

In [15]:
print(real_data.dtypes, '\n', synthetic_data.dtypes)
print(real_data.shape, synthetic_data.shape)

group    category
sbp1      float64
sbp2      float64
sbp3      float64
sbp4      float64
dbp1      float64
dbp2      float64
dbp3      float64
dbp4      float64
dtype: object
 group     object
sbp1     float64
sbp2     float64
sbp3     float64
sbp4     float64
dbp1     float64
dbp2     float64
dbp3     float64
dbp4     float64
dtype: object
(2717, 9) (2717, 9)

In [16]:
real_data.describe()

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
count,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,0.072962,-0.015681,0.030675,0.038696,0.057982,-0.056777,0.022021,0.028471
std,4.086347,0.729714,0.509026,0.262684,3.710970,0.733119,0.371803,0.180631
min,-18.884976,-2.732794,-2.023219,-1.289887,-17.202625,-2.580206,-1.409579,-0.862115
25%,-2.674316,-0.470025,-0.306902,-0.126936,-2.352459,-0.519699,-0.224223,-0.085791
50%,0.301318,-0.016234,0.026003,0.034561,0.244464,-0.044513,0.016090,0.032382
75%,2.979693,0.441029,0.354509,0.202381,2.653050,0.436457,0.258646,0.144028
max,11.023203,3.680704,2.233565,1.292367,12.307994,2.916243,1.550258,0.852724

In [17]:
synthetic_data.describe()

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
count,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,-6.545010,-0.166566,-0.943665,-0.438473,-2.382584,0.047471,-0.707441,-0.452380
std,1.270916,0.246834,0.074659,0.023709,1.340194,0.166894,0.062523,0.062874
min,-10.856389,-1.076968,-1.140287,-0.524440,-6.406606,-0.449554,-0.830323,-0.614850
25%,-7.379457,-0.322643,-0.998965,-0.453333,-3.322200,-0.072497,-0.753020,-0.500338
50%,-6.385706,-0.145956,-0.944058,-0.437415,-2.334186,0.033317,-0.721513,-0.456873
75%,-5.620048,0.009020,-0.892253,-0.422970,-1.398292,0.152602,-0.674768,-0.408747
max,-3.195981,0.513354,-0.678357,-0.355833,1.362300,0.688730,-0.385679,-0.219501

In [18]:
synthetic_data.groupby('group').count()

        sbp1  sbp2  sbp3  sbp4  dbp1  dbp2  dbp3  dbp4
group
Group0  2670  2670  2670  2670  2670  2670  2670  2670
Group1    47    47    47    47    47    47    47    47

In [19]:
#Save generated samples
synthetic_data.to_csv(SYN_DATA_HOME + SYNTHETIC_FILE, index=False)